name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Space (clean deploy without screenshots)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "fahmiyacm@gmail.com"
          git config --global user.name "Fahmiyacm"

          # Create a new branch from main for deployment
          git checkout -b hf-deploy

          # Remove screenshots only from Git tracking (not deleting local files)
          git rm -r --cached Screenshots/
          git commit -m "Remove screenshots for HF deploy" || echo "No changes to commit"

          # Add Hugging Face remote
          git remote add space https://Fahmiyacm:${HF_TOKEN}@huggingface.co/spaces/Fahmiyacm/shawarma-admin-app

          # Push this cleaned branch to HF main
          git push --force space hf-deploy:main
