- name: Push to Hugging Face Space
  env:
    HF_TOKEN: ${{ secrets.HF_TOKEN }}
  run: |
    git config --global user.email "actions@github.com"
    git config --global user.name "GitHub Actions"

    # Create a temporary branch for HF without screenshots
    git checkout -b hf-deploy
    git rm -r --cached screenshots/
    git commit -m "Remove screenshots for Hugging Face deployment" || echo "No changes to commit"

    git remote add space https://Fahmiyacm:${HF_TOKEN}@huggingface.co/spaces/Fahmiyacm/shawarma-admin
    git push --force space hf-deploy:main
